# Numpy

Use numpy because:

- it's compact
- it's fast
- it matches the way we think about math

# Why not just use Python?

![Floating Point](data/img/C-Python-Float.png)

![List](data/img/Python-List-Float.png)

![List](data/img/Numpy-Array.png)

In [1]:
!pip install numpy

Looking in links: /Users/rick446/src/wheelhouse
You should consider upgrading via the '/Users/rick446/.virtualenvs/py38/bin/python3.8 -m pip install --upgrade pip' command.


# "How fast is it?"

In [2]:
import numpy as np

np.random.seed(0)

def reciprocate(values):
    """Returns an array of 1.0/x for every x in values"""
    result = np.empty(len(values))
    for i, x in enumerate(values):
        result[i] = 1.0 / x
    return result

reciprocate(np.random.randint(1, 10, 10))

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ,
       0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [3]:
xs = np.random.randint(1, 10, 1_000_000)

In [4]:
%timeit reciprocate(xs)

7.04 s ± 618 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit 1.0 / xs

11.2 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


# How compact is it?

In [6]:
!pip install pympler

Looking in links: /Users/rick446/src/wheelhouse
You should consider upgrading via the '/Users/rick446/.virtualenvs/py38/bin/python3.8 -m pip install --upgrade pip' command.


In [7]:
from pympler.asizeof import asizeof

In [8]:
asizeof(1.1)

24

In [9]:
asizeof([])

56

In [10]:
np_array_size = asizeof(xs)
np_array_size

8000096

In [11]:
import random
py_list_size = asizeof([random.random() for i in range(1_000_000)])

In [12]:
py_list_size

32697456

In [13]:
py_list_size / np_array_size

4.087132954404547

In [14]:
from collections import deque, namedtuple

deck = deque([])
Point = namedtuple('Point', 'x y')

In [15]:
asizeof([])

56

In [16]:
asizeof(())

40

In [17]:
asizeof((1,2))

120

In [18]:
asizeof(Point(1,2))

120

In [19]:
asizeof(deck)

624

In [20]:
asizeof({})

64

In [21]:
asizeof(set())

216

In [22]:
import array

In [23]:
array?

# "Rounding"

In [26]:
x = 1.234
np.trunc(x)

1.0

In [27]:
np.trunc(-x)

-1.0

In [28]:
np.floor(x)

1.0

In [29]:
np.floor(-x)

-2.0

In [30]:
np.ceil(x)

2.0

In [31]:
np.ceil(-x)

-1.0

In [32]:
np.round(x)

1.0

In [33]:
np.round(-x)

-1.0

In [34]:
np.round([1.5, 2.5])

array([2., 2.])

In [35]:
[round(1.5), round(2.5)]

[2, 2]

# Creating Numpy arrays

In [36]:
xs = np.array(range(5))
xs, xs.dtype

(array([0, 1, 2, 3, 4]), dtype('int64'))

In [37]:
xs = np.array([1,2,3,4,3.14])
xs, xs.dtype

(array([1.  , 2.  , 3.  , 4.  , 3.14]), dtype('float64'))

In [38]:
xs = np.array(range(5), dtype=float)
xs, xs.dtype

(array([0., 1., 2., 3., 4.]), dtype('float64'))

In [39]:
xs = np.array(range(5), dtype=np.int8)
xs, xs.dtype

(array([0, 1, 2, 3, 4], dtype=int8), dtype('int8'))

In [40]:
xs = np.array([0, 0, 1, 1], dtype=np.int0)
xs, xs.dtype

(array([0, 0, 1, 1]), dtype('int64'))

In [41]:
%timeit np.empty(1_000_000)

69.7 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [42]:
%timeit np.zeros(1_000_000)

5.22 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Multi-dimensional arrays

In [43]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

Quick array creation convenience methods

In [44]:
np.zeros(20, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [45]:
np.ones((3, 4), dtype=np.float128)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float128)

In [46]:
np.ones((3, 4, 5), dtype=np.float128)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float128)

In [47]:
xs = np.full((3,4), np.pi)
xs

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [48]:
xs.shape

(3, 4)

In [49]:
len(xs)

3

# Creating ranges of array values

In [50]:
range(10)

range(0, 10)

In [51]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [56]:
np.arange(10, 50, 5.5)

array([10. , 15.5, 21. , 26.5, 32. , 37.5, 43. , 48.5])

In [57]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [58]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# The `r_` and `c_` helpers

In [59]:
np.r_

In [60]:
np.r_[:5]

array([0, 1, 2, 3, 4])

In [61]:
np.r_[:5, 200, :5]

array([  0,   1,   2,   3,   4, 200,   0,   1,   2,   3,   4])

In [62]:
np.r_[[1,2,3], [10, 11], 5:1:-0.3]

array([ 1. ,  2. ,  3. , 10. , 11. ,  5. ,  4.7,  4.4,  4.1,  3.8,  3.5,
        3.2,  2.9,  2.6,  2.3,  2. ,  1.7,  1.4,  1.1])

In [63]:
np.r_[0:10:3]

array([0, 3, 6, 9])

In [64]:
np.r_[0:10:3j]   # abusing indexing _and_ complex numbers now

array([ 0.,  5., 10.])

In [68]:
(np.r_[0:10:20j] == np.linspace(0, 10, 20)).all()

True

In [71]:
np.r_[0:10:20]

array([0])

In [72]:
np.c_[:10, :100:10j]

array([[  0.        ,   0.        ],
       [  1.        ,  11.11111111],
       [  2.        ,  22.22222222],
       [  3.        ,  33.33333333],
       [  4.        ,  44.44444444],
       [  5.        ,  55.55555556],
       [  6.        ,  66.66666667],
       [  7.        ,  77.77777778],
       [  8.        ,  88.88888889],
       [  9.        , 100.        ]])

In [73]:
np.c_[:10]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Fast generation of random values

In [74]:
np.random.random((4,4))

array([[0.80351516, 0.44480604, 0.66925971, 0.63053011],
       [0.65843811, 0.24503895, 0.27820458, 0.44202878],
       [0.579177  , 0.29078652, 0.3035797 , 0.13168765],
       [0.46878437, 0.85192625, 0.79180773, 0.75873527]])

In [75]:
np.random.normal(10, 2, (3,3))

array([[11.22273148, 10.2920636 ,  9.79183757],
       [10.70956785, 12.26631001, 11.04919632],
       [ 8.59264221,  7.60657508,  9.39315149]])

In [76]:
np.random.randn(10)

array([-2.24767417,  0.36273125, -1.69640798,  1.3107156 , -0.81141234,
        0.03317467, -0.3370064 ,  0.38684747,  0.014802  ,  0.16753439])

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Converting array types

In [82]:
xs = np.r_[:10:20j]
xs

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [83]:
np.round(xs).astype(int)

array([ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

# Numpy indexing and slicing

In [84]:
xs = np.random.randint(1, 10, (4, 4))
xs

array([[5, 3, 6, 5],
       [3, 5, 7, 9],
       [3, 9, 3, 5],
       [6, 1, 2, 6]])

In [85]:
xs[1, 1]

5

In [86]:
xs[1]

array([3, 5, 7, 9])

In [87]:
xs[:,1]

array([3, 5, 9, 1])

In [88]:
xs[1:3,1:3]

array([[5, 7],
       [9, 3]])

In [89]:
xs[[1,2], 2]

array([7, 3])

Lists for all indexes work a little different

In [90]:
xs[[1,2], [3,2]]

array([9, 3])

In [91]:
xs

array([[5, 3, 6, 5],
       [3, 5, 7, 9],
       [3, 9, 3, 5],
       [6, 1, 2, 6]])

In [92]:
xs[1, 3], xs[2, 2]

(9, 3)

In [93]:
xs.reshape(16)

array([5, 3, 6, 5, 3, 5, 7, 9, 3, 9, 3, 5, 6, 1, 2, 6])

In [94]:
xs.ravel()

array([5, 3, 6, 5, 3, 5, 7, 9, 3, 9, 3, 5, 6, 1, 2, 6])

In [95]:
np.r_[:9].reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Sometimes you need to take a 1-D array and make a column vector out of it:

In [96]:
xs = np.r_[:10]
xs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
xs[:, None]    

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [98]:
xs[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [99]:
print(np.newaxis)

None


In [100]:
np.c_[xs]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Filtering

In [101]:
xs = np.random.randint(0, 5, 10)

In [102]:
xs

array([2, 1, 2, 3, 0, 0, 2, 2, 3, 0])

In [103]:
xs.nonzero()

(array([0, 1, 2, 3, 6, 7, 8]),)

In [104]:
xs[xs.nonzero()]

array([2, 1, 2, 3, 2, 2, 3])

In [105]:
xs[xs != 0]

array([2, 1, 2, 3, 2, 2, 3])

In [106]:
xs < 3

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True])

In [107]:
xs[xs < 3]

array([2, 1, 2, 0, 0, 2, 2, 0])

In [108]:
xs = np.random.randint(0, 5, (3, 3))
xs

array([[0, 4, 2],
       [1, 3, 0],
       [2, 3, 2]])

In [109]:
xs.nonzero()

(array([0, 0, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 0, 1, 2]))

In [110]:
np.array(xs.nonzero())

array([[0, 0, 1, 1, 2, 2, 2],
       [1, 2, 0, 1, 0, 1, 2]])

In [111]:
xs[xs.nonzero()]

array([4, 2, 1, 3, 2, 3, 2])

Maybe this looks a little cleaner?

In [112]:
np.transpose(xs.nonzero())

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1],
       [2, 2]])

In [113]:
xs[xs.nonzero()] = 100
xs

array([[  0, 100, 100],
       [100, 100,   0],
       [100, 100, 100]])

In [114]:
xs = np.random.random((4,4))
xs

array([[0.32436191, 0.53893595, 0.01408881, 0.39938235],
       [0.05864118, 0.35265169, 0.57356318, 0.2848448 ],
       [0.78065751, 0.78120433, 0.97550984, 0.11864333],
       [0.89353627, 0.93887408, 0.17153379, 0.86606886]])

In [115]:
xs[xs > 0.7] = 0.7
xs

array([[0.32436191, 0.53893595, 0.01408881, 0.39938235],
       [0.05864118, 0.35265169, 0.57356318, 0.2848448 ],
       [0.7       , 0.7       , 0.7       , 0.11864333],
       [0.7       , 0.7       , 0.17153379, 0.7       ]])

# Array views

In [116]:
xs = np.r_[:16].reshape((4,4))
xs

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
xs_view = xs[1:3,1:3]
xs_view

array([[ 5,  6],
       [ 9, 10]])

In [118]:
xs_view[0,0] = 100
xs_view

array([[100,   6],
       [  9,  10]])

In [119]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [120]:
xs_view_copy = xs_view.copy()

In [121]:
xs_view_copy[0, 0] = 200
xs_view_copy

array([[200,   6],
       [  9,  10]])

In [122]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [123]:
xs_view

array([[100,   6],
       [  9,  10]])

# Numpy universal functions (ufuncs)

Most `np.array` methods also exist as functions in the numpy namespace.

They typically operate well over scalars, numpy arrays, and Python sequences

In [124]:
np.multiply(2, 3)  # scalar / scalar

6

In [125]:
np.multiply(np.r_[:10], 20) # array / scalar

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [126]:
np.multiply(np.r_[:10], [4] * 10)  # array / list

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [127]:
np.divide(1, 0)

<ipython-input-127-02e332739a16>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, 0)


inf

In [128]:
np.divide([1], [0])

<ipython-input-128-3819d6251caa>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide([1], [0])


array([inf])

In [129]:
np.divide(1, 0) - np.divide(1, 0)

<ipython-input-129-b6ff1807cfcc>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, 0) - np.divide(1, 0)
<ipython-input-129-b6ff1807cfcc>:1: RuntimeWarning: invalid value encountered in double_scalars
  np.divide(1, 0) - np.divide(1, 0)


nan

In [130]:
1 / np.zeros(10)

<ipython-input-130-f31516081096>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / np.zeros(10)


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [131]:
1 // np.r_[0]

<ipython-input-131-0c31686b367a>:1: RuntimeWarning: divide by zero encountered in floor_divide
  1 // np.r_[0]


array([0])

In [133]:
2 ** np.r_[:9].reshape((3,3))

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

https://docs.scipy.org/doc/numpy/reference/ufuncs.html for the full list of ufuncs

Generally, operators delegate to ufuncs if at least one side of the operation is a numpy type.

# Aggregation

We can apply ufuncs as reduction operators:

In [134]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [135]:
np.add.reduce(xs)

array([ 24, 123,  32,  36])

In [136]:
np.add.reduce(xs, axis=1)

array([  6, 117,  38,  54])

In [137]:
np.multiply.reduce(xs)

array([    0, 11700,  1680,  3465])

In [138]:
np.multiply.reduce(xs, axis=1)

array([    0, 16800,  7920, 32760])

In [144]:
np.sum(xs)

215

In [141]:
np.mean(xs)

13.4375

In [142]:
np.mean(xs, axis=0)

array([ 6.  , 30.75,  8.  ,  9.  ])

In [143]:
np.mean(xs, axis=1)

array([ 1.5 , 29.25,  9.5 , 13.5 ])

# Build your own ufunc

Although this does _not_ give you "compiled C" performance, you can get the casting rules for your own functions using `np.vectorize`

In [145]:
def saturating_adder(maxval):
    def add(x, y):
        return min([x+y, maxval])
    return np.vectorize(add)
    

In [146]:
myadd = saturating_adder(10)

In [147]:
myadd(2, 9)

array(10)

In [148]:
myadd([2,3,4,5], 6)

array([ 8,  9, 10, 10])

In [149]:
myadd([2,3,4,5], np.r_[5:9])

array([ 7,  9, 10, 10])

Open the [numpy lab][numpy-lab]

[numpy-lab]: ./numpy-lab.ipynb