# Exercise: Numpy

Create an array of 10 zeros

In [1]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of size 10 with zeros everywhere but the 7th position, which should be 3.14

In [2]:
x = np.zeros(10)
x[7] = 3.14
x

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14, 0.  , 0.  ])

In [3]:
np.r_[[0] * 7, 3.14, [0] * 2]

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 3.14, 0.  , 0.  ])

Create an array with values in the range [30, 40) (not including 40)

In [4]:
x = np.r_[30:40]
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [5]:
np.arange(30, 40)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [6]:
np.array(range(30, 40))

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

Reverse the array you just created

In [7]:
x[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30])

In [8]:
np.flip(x)

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30])

Create a 4 x 4 matrix with values from 0 to 15 (inclusive)

In [9]:
np.r_[:16].reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Find the indices of the nonzero elements in the following array:

In [10]:
x = [1, 2, 0, 1, 0, 0, 1]

In [11]:
np.nonzero(x)

(array([0, 1, 3, 6]),)

Create a 5x5 identity matrix

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a 2 x 3 x 4 array with random values

In [14]:
x = np.random.random((2,3,4))
x

array([[[0.67087245, 0.51334838, 0.53201042, 0.8767497 ],
        [0.44516115, 0.20877649, 0.17345871, 0.54488987],
        [0.8204373 , 0.05445445, 0.07770339, 0.687987  ]],

       [[0.98376083, 0.80987407, 0.61570137, 0.37893928],
        [0.27214525, 0.34536885, 0.01438207, 0.36521137],
        [0.40370118, 0.55920343, 0.27651963, 0.90781653]]])

Find the minimum and maximum values in your last array

In [15]:
x.min(), x.max()

(0.014382069814711351, 0.9837608294458938)

In [16]:
np.min(x), np.max(x)

(0.014382069814711351, 0.9837608294458938)

Create a vector with 100 random values from the normal function with mean 0 and standard deviation 6

In [17]:
x = np.random.normal(loc=0, scale=6, size=100)
x

array([  5.9627021 ,   3.2614089 ,  -3.06092204,   4.64756599,
         3.66918776,  -0.3691082 ,   1.31794642,  -2.10533074,
       -11.29520778, -11.12442829,   5.12904998,  -4.65586198,
        -1.18397283,   3.00719616,   1.69292184,   7.52867324,
        -2.67022296,   5.87441996,  -8.37079895,  -3.12081056,
       -10.4882287 ,   5.8511239 ,   4.04456128,  -0.84598339,
         4.7553236 ,   1.23607778,   6.28172894,   3.26374025,
         1.96855241,   1.93351571,   0.10505036, -11.75577528,
         2.01438662,  -5.46916278,  -4.21108458,   6.84267496,
         6.79173459,   5.64826788,  -7.59320414,   2.78830482,
        -1.80267193,  -8.09596691,  -7.68301116,  -4.44699363,
         5.61875887,  -3.89953847, -16.58431279, -10.45993307,
        -0.75981466,   5.1247633 ,  -5.11291288,   5.85875108,
         4.97842345,  -2.08056636,  -7.16926856,   7.96958631,
         3.94975768,   2.96174458,  11.10902663,  -8.36257977,
        -2.148868  ,   2.6313176 ,   3.29113392,  -7.15

Calculate the actual mean and standard deviation of the vector you created

In [18]:
x.mean(), x.std()

(0.651372865818092, 6.0899309219545215)

In [19]:
np.mean(x), np.std(x)

(0.651372865818092, 6.0899309219545215)

Create a 8 x 8 array with 10's around the edges and np.pi in the middle

In [20]:
x = np.full((8,8), 10.0)
x[1:-1,1:-1] = np.pi
x

array([[10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        , 10.        , 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        ,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265, 10.        ],
       [10.        , 10.        , 10.        , 10.        , 10.        ,
        10.        , 10.        , 10.        ]])

Try to predict the outcome of the following before running them:

In [21]:
0 * np.nan

nan

In [22]:
np.nan == np.nan

False

In [23]:
np.inf == np.inf

True

In [24]:
np.inf - np.inf

nan

In [25]:
0.1 * 3 == 0.3

False

In [30]:
def almost_equal(x, y):
    return abs(x-y) < 1e-7

In [31]:
almost_equal(0.1 * 3, 0.3)

True

In [32]:
import unittest
unittest.TestCase().assertAlmostEqual(0.3, 0.1 * 3)

In [26]:
np.array(0) // np.array(0)

<ipython-input-26-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [27]:
np.array(0) // np.array(0.0)

nan

In [28]:
np.array(0) / np.array(0)

<ipython-input-28-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [29]:
np.array(0.0) / np.array(0.0)

<ipython-input-29-93b8fe404e2e>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0.0) / np.array(0.0)


nan

Create an array of 10 values from 0 to 1, both included

In [33]:
np.r_[0:1:10j]

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [34]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

De-mean each row of the following matrix:

In [35]:
m = np.random.rand(4, 4)
m

array([[0.69775194, 0.931309  , 0.5763409 , 0.89416447],
       [0.73257498, 0.95892726, 0.09380268, 0.56355903],
       [0.05121963, 0.28179402, 0.65951137, 0.78216202],
       [0.37097382, 0.93324672, 0.39611795, 0.31574114]])

In [36]:
m.mean(axis=1)

array([0.77489158, 0.58721599, 0.44367176, 0.50401991])

In [37]:
m.mean(axis=1, keepdims=True)

array([[0.77489158],
       [0.58721599],
       [0.44367176],
       [0.50401991]])

In [38]:
demean_m = m - m.mean(axis=1, keepdims=True)
demean_m

array([[-0.07713964,  0.15641743, -0.19855068,  0.11927289],
       [ 0.14535899,  0.37171127, -0.49341331, -0.02365695],
       [-0.39245213, -0.16187774,  0.21583961,  0.33849026],
       [-0.13304609,  0.42922681, -0.10790196, -0.18827877]])

In [39]:
demean_m.mean(axis=1)

array([-5.55111512e-17,  2.77555756e-17, -2.77555756e-17,  5.55111512e-17])